dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $APP
  skip_cleanup: true
  on:
    branch: main